### ISSUE TITLE
SearchField component

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-design-system#123]
Implement a SearchField component to be used for searching in new authorisation pages.
(Previousy "Implement Icon left and right" but since the icons have yet to be implemented into the design system and an argument can be made that a search field is needed as a separate component anyway, this has been changed to minimize complications and double work)

The component should wrap the TextField component, but display a search icon (to the far right of the text box)

![image.png](https://images.zenhubusercontent.com/633168749a1e69588020c073/1204f423-97bc-4862-bdb4-b526c80caeb2)

### Tasks
- [x] Speak to designsystem-senior to get their notes and go-ahead on the task
- [x] Speak to UX to get their notes and go-ahead on the task
- [x] Implement the component
- [x] Implement tests for the component

**Comment by hannekristin** [comment]
@Albertlarsen I storybook er denne uten label: ![image.png](https://images.zenhubusercontent.com/6333ed956083c740244ee3ca/249d7493-d827-4159-ac8a-d5c2081ecb33) Er det riktig? I DDS skal det være mulig å ha label og beskrivende tekst, samt mulighet for ikon i begge sider

**Comment by allinox** [comment]
@hannekristin 
Hva er det du sikter til når du sier label?

Dette er ikke en komponent ment for å ha et gitt ikon på enten venstre eller høyre, det ville evt. vært en utvidelse av vanlig input-field som var det vi opprinnelig så på å gjøre.
Men siden ikoner ikke er klart i designsystemet enda kunne ikke det gjennomføres slik, og i snakk med Håkon bestemte vi oss for heller å lage et egen søkefelt med hardkodet symbol. (siden det er det som er viktigst for oss i dette tilfellet og det kan være greit å ha en slik komponent senere uansett hvis man ønsker å videreutvikle søkefelt til en mer avanseert variant)
Denne er pr nå litt som en variant av TextField-komponenten som du også kan finne i Storybook. 🙂

**Comment by Albertlarsen** [comment]
@allinox Hun tenker på denne labelen i bildet under tenker jeg. Jeg er enig i at komponenten bør få en label. 

@hannekristin Når det kommer til ikon på begge sider så blir det som Alexandra nevner at den er hardkodet i starten frem til ikoner er ferdig i DS.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/31471142/197177113-a2322cc6-9594-4896-9077-d04db8af6b5a.png">

**Comment by allinox** [comment]
@Albertlarsen 

Men TextField og TextArea -komponentene i Storybook har ikke en sånn label den heller. (En kan jo forsåvidt diskutere om det er riktig å h det sånn, men jeg antok at det var det som var standarden pr nå ihvertfall 😅)
TextField:
![image.png](https://images.zenhubusercontent.com/633168749a1e69588020c073/32a813a2-79e7-419c-8394-4e7f1acb33f0)

**Comment by Magnusrm** [comment]
Når TextField komponenten ble laget så eksisterte ikke de skissene som du refererte til. Textfield ble laget i forbindelse med disse skissene: https://www.figma.com/file/wnBveAG2ikUspFsQwM3GNE/Altinn-Studio-Apps?node-id=12857%3A8186

Forøvrig så er komponentene i studio implementert på en måte slik at hver komponent får label håndtert av en generell komponent som wrapper hver av de simpleste komponentene, så det har ikke vert like nødvendig for oss og dermed kanskje ikke tenkt over da denne ble designet/laget.

**Comment by Albertlarsen** [comment]
Vi laget nytt issue for å legge til label #162 @hannekristin. Kan du close issuen her(med mindre det er noe andre kommentarer i tillegg til dette med label) så tar vi det rundt labelen i den nye issuen? :)
