### ISSUE TITLE
Stop using PnP/Zero installs

### ISSUE THREAD

**Issue by haakemon** [Altinn/altinn-design-system#35]
### Description

Yarn PnP/Zero installs is in many ways great - you wont have to run `yarn install` when switching branches just in case the branch has different dependencies. The dependencies are part of the git history.

However, this causes lots of other issues;
- The repo grows vastly in size, so cloning the repo takes a long time (you could argue thats not really important, since you dont typically clone a repo often enough for it to become annoying)
- `npm link`/`yarn link` doesnt work properly
- Rollup terser plugin doesnt work (although @nemzes made a fix for this repo 🥇)
- The language server in VS Code crashes when trying to navigate to 3rd party components
- Cannot navigate to other 3rd party resources (f.ex css files) in VS Code
- PR's are littered with irrelevant files when bumping versions for dependencies in package.json (see example here: https://github.com/Altinn/altinn-design-system/pull/34/files)

The benefits just dont outweigh the drawbacks, so we should switch to plain old `node_modules` approach.

### Tasks

- [x] Use `nodeLinker: 'node-modules'` in .yarnrc.yml
- [x] Update .gitignore with the correct files to ignore
- [x] ~~Check if there is a way to remove the binary files already added to git history to reduce the size of the repository. If this turns out to be impossible without rewriting git history on main branch, we probably should not do it.~~
	- This is not possible without rewriting history. Leave it as-is for now, and consider rewriting history later if it seems worth it, because its disruptive to all users.

**Comment by nemzes** [comment]
I concur. The main advantage I see with PnP is security, but there are too many issues for now.
